### ISSUE TITLE
Some glyphs are shifted to the right when rendered in Minecraft

### ISSUE THREAD

**Issue by arm32x** [IdreesInc/Monocraft#11]
Glyphs affected include `i`, `j`, `k`, `l`, `:`, `.`, and probably others I haven't mentioned. Here is a screenshot showing the issue on the pause menu and the F3 debug menu:

![Screenshot](https://i.imgur.com/UjBR1SY.png)

I am using version 1.1. The font was added to the game using the [instructions on the Minecraft Wiki](https://minecraft.fandom.com/wiki/Resource_Pack#Fonts) with the following JSON file:

```json
{
    "providers": [
        {
            "type": "ttf",
            "file": "monocraft.otf",
            "shift": [0, 1],
            "size": 9,
            "oversample": 9
        }
    ]
}
```

**Comment by bMorgan01** [comment]
Same for non-minecraft, the programming ligatures shift to the right

**Comment by IdreesInc** [comment]
I never considered someone would be insane enough to try to put this font back into Minecraft. There's a good chance this can't be fixed due to that space being required for those characters to render properly in a monospaced vector font. I'm not sure the process by which Minecraft is turning the font into a bitmap font, but I suspect that fixing it might not be possible without breaking the font for normal usage.
@bMorgan01 If you are still encountering this issue, feel free to make another issue on this repo and include screenshots of what you are seeing.
