### ISSUE TITLE
.otf build has some characters with missing holes

### ISSUE THREAD

**Issue by IdreesInc** [IdreesInc/Monocraft#110]
**Describe the bug**
The .otf build shows characters like 8, o, and O with filled in holes. This does not show up in the .ttf build for some reason.

**Screenshots**
<img width="501" alt="Screen Shot 2023-02-12 at 4 19 56 PM" src="https://user-images.githubusercontent.com/4875804/218337862-26066797-b745-46be-987c-ca66ad76fa6d.png">

**Operating system**
MacOS

**Comment by Dheatly23** [comment]
Oddly enough, this is not on windows though.

![image](https://user-images.githubusercontent.com/71598333/218353711-9b2712ec-b7b0-406a-a2b4-997e9cba2eb7.png)

I think it's because of differences in how the renderer treats holes. I suspect if the winding of holes is reversed it would solve it. Another solution is to merge polygons whenever possible. The latter is still being developed in my fork.

PS: Just tested reversing windings, it does not affect `.otf`, but it broke `.ttf`.
