### ISSUE TITLE
Add continuous ligatures for equal sign (=)

### ISSUE THREAD

**Issue by Scrumplex** [IdreesInc/Monocraft#12]
I think it would be nicer, if equal signs were connected instead of having chunks of triple-equal-signs.

`===` should still become `≣≣≣`
but `====` and longer should be `====`

Monocraft:
![Equal signs with Monocraft](https://scrumplex.rocks/img/1662545471.png)

Fira Code:

![Equal signs with Fira Code](https://scrumplex.rocks/img/1662545545.png)

**Comment by IdreesInc** [comment]
I wonder how Fira Code does this. If it is due to some script automatically generating ligatures for arbitrary lengths of that character, I will not be able to add that to this font since it was made by hand. However, if it is just using a feature of OpenTypeFonts that I'm not aware of, then I would be happy to add it.

**Comment by MCFX2** [comment]
An alternative approach (and what I'd prefer) is dong what JetBrains Mono does with these:
![image](https://user-images.githubusercontent.com/20264064/189554157-8695511c-3043-4733-acd9-181cc055ecd7.png)

This might be easier to implement in practice.

**Comment by IdreesInc** [comment]
Turns out this requires complex character substitution, and as such is pretty much blocked until I can figure out #77

**Comment by IdreesInc** [comment]
Partially complete as part of #116
