### ISSUE TITLE
Support for different styles (Italics, Bold etc)

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [IdreesInc/Monocraft#127]
Could Bold, Italics, Underlined and Strikethrough be added? From what I understand these styles are currently not included.

**Comment by Dheatly23** [comment]
Normally, font renderers are able to "bold" and "italic" fonts automatically. But sometimes it can go bad.

Italicizing is quite easy, just slant the grid by let's say 15 degrees. Bold can be done by expanding the lines by small amount. Underline and strikethrough is already automatic, since it's just a simple line.

As far as my research goes, Fontforge can't pack all variants into a single file. So there will be a separate file for italic and bold variant.

**Comment by LevitatingBusinessMan** [comment]
> Normally, font renderers are able to "bold" and "italic" fonts automatically. But sometimes it can go bad.

From my testing Alacritty isn't able to do this. Could be a limitation of Alacritty, I can look into that.

**Comment by Dheatly23** [comment]
I have tested some ideas and it _might_ work. It's on my fork at branch `new-ligatures`. I maybe put a proper PR later.

**Comment by SirMishaa** [comment]
As far as I'm concerned, the rendering is already good, but it would be much better if the text were a little more bold. 

If anyone has solutions for this, I'd be interested.

**Comment by IdreesInc** [comment]
Done as of https://github.com/IdreesInc/Monocraft/releases/tag/v4.0!

**Comment by LevitatingBusinessMan** [comment]
glad to see this one closed
thanks @IdreesInc 

I unironically really like Monocraft. I like it far more than Scientifica. I recently configured Firefox to show any Monospace or Serif fonts as Monocraft lol. I also use it as my system theme via GTK.
