### ISSUE TITLE
Would you be open to adding new ligatures or merging PRs for them?

### ISSUE THREAD

**Issue by mainrs** [IdreesInc/Monocraft#14]
I write some Haskell code. Having some ligatures for stuff like `<$>`, `>>=`, `<>`, `<+>`, `>>` and more. FiraCode has a cool section about language-specific ligatures.

![image](https://user-images.githubusercontent.com/5113257/188882514-d9b4a50e-cd9b-4cf4-aa5f-b70a0bf150c5.png)
Source: https://github.com/tonsky/FiraCode

**Comment by IdreesInc** [comment]
I would be open to this if I can properly make a script for creating a non-ligature version of the font. That way those that don't like ligatures don't have to be inundated with too many different combinations.
Blocked by https://github.com/IdreesInc/Monocraft/issues/39

**Comment by IdreesInc** [comment]
Monocraft is now made by a script and as of 2.1 will include a non-ligature version by default. As such, anyone is welcome to request new ligatures to be added, though I would **highly** suggest making an issue first before making the PR so that we can gauge whether the ligature would be a good idea or not.
