### ISSUE TITLE
Add Font to Google

### ISSUE THREAD

**Issue by JollyJolli** [IdreesInc/Monocraft#144]
### Request: Add Font to Google Fonts Repository

**Dear Monocraft Team,**

I'm reaching out to request adding your font to Google Fonts. Google Fonts is a widely-used platform for fonts, providing accessibility and visibility to a global audience.

#### Why Google Fonts?

Your font's unique style would be a great addition to the diverse collection on Google Fonts. 

#### How to Proceed

To submit your font, please follow the guidelines on [Google Fonts GitHub](https://github.com/google/fonts).

Thank you for considering this request!

**Best,**
Jolly

**Comment by IdreesInc** [comment]
Hello! I'm not sure Google Fonts would allow Monocraft to be added due to the association with Minecraft. They'd be more likely to add [Miracode](https://github.com/IdreesInc/Miracode) in the future possibly.
However, if they would be willing to add the font, I'd be more than happy to work with them to do so!

**Comment by JollyJolli** [comment]
Thank you!
